[uwsgi]
chdir = /var/www/kasekhair_damietta_port
home = /var/www/kasekhair_damietta_port/venv
module = config.wsgi:application
master = true
processes = 2
threads = 1
max-requests = 100
harakiri = 30
lazy-apps = true
socket = /var/www/kasekhair_damietta_port/kased.sock
chmod-socket = 666
vacuum = true
die-on-term = true
