# Generated by Django 6.0.4 on 2026-04-19 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الأسبوع (الأربعاء)')),
                ('active_group', models.CharField(choices=[('A', 'جروب A هو اللي شغال'), ('B', 'جروب B هو اللي شغال')], max_length=1, verbose_name='المجموعة العاملة')),
            ],
        ),
        migrations.CreateModel(
            name='Dredger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vessel_phone', models.CharField(default='01XXXXXXXXX', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_operators', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('dredger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dredger')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم بالكامل')),
                ('group', models.CharField(choices=[('A', 'جروب A'), ('B', 'جروب B')], max_length=1, verbose_name='المجموعة (الوردية)')),
                ('team_type', models.CharField(choices=[('dredger', 'طاقم كراكة'), ('pipe', 'طاقم خط بحري (Pipe Fighter)')], max_length=10, verbose_name='نوع الطاقم')),
                ('role', models.CharField(choices=[('operator', 'مشغل'), ('marine', 'بحرية'), ('mechanic', 'ميكانيكا'), ('admin', 'إداري/سائق')], max_length=30, verbose_name='الوظيفة')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PipeFighterOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('shift', models.CharField(choices=[('morning', 'نهار'), ('night', 'ليل')], max_length=10)),
                ('total_line_length', models.FloatField(verbose_name='طول الخط')),
                ('active_joints', models.IntegerField(verbose_name='الوصلات')),
                ('spare_pipes', models.IntegerField(default=0)),
                ('spare_rubbers', models.IntegerField(default=0)),
                ('discharge_pipes', models.IntegerField(default=0)),
                ('discharge_rubbers', models.IntegerField(default=0)),
                ('scrapped_pipes', models.IntegerField(default=0)),
                ('scrapped_rubbers', models.IntegerField(default=0)),
                ('work_photos', models.ImageField(blank=True, null=True, upload_to='pf_daily/')),
                ('daily_notes', models.TextField(blank=True, null=True)),
                ('crew_present', models.ManyToManyField(limit_choices_to={'team_type': 'pipe'}, related_name='pf_present', to='core.staff')),
                ('operator_in_charge', models.ForeignKey(limit_choices_to={'team_type': 'pipe'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='المشغل المسؤول')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_time', models.CharField(choices=[('morning', 'نهار'), ('night', 'ليل')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('quantity_m3', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', 'في الخدمة'), ('stopped', 'متوقفة')], default='active', max_length=10)),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'operator', 'team_type': 'dredger'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff')),
                ('report_24h', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.dailyprojectreport')),
            ],
        ),
    ]
