# Generated by Django 6.0.4 on 2026-05-11 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='اسم الموظف')),
                ('username', models.CharField(max_length=50, verbose_name='اسم المستخدم')),
                ('password_plain', models.CharField(max_length=50, verbose_name='كلمة المرور (للتذكير)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سجل حساب سري',
                'verbose_name_plural': 'خزنة الحسابات السرية',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصنف')),
                ('category', models.CharField(choices=[('قايش', 'قايش'), ('أقفال', 'أقفال'), ('حبال', 'حبال'), ('مسامير', 'مسامير'), ('وايرات', 'وايرات'), ('مفاتيح ولقم', 'مفاتيح ولقم'), ('ربرات', 'ربرات'), ('طوافات', 'طوافات'), ('أخرى', 'أخرى')], max_length=50, verbose_name='القسم')),
                ('quantity', models.FloatField(default=0, verbose_name='الرصيد الحالي بالموقع')),
            ],
        ),
        migrations.CreateModel(
            name='MarineInventoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الجرد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
        ),
        migrations.CreateModel(
            name='NewsTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='التعليمات / الخبر')),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'شريط أخبار',
                'verbose_name_plural': 'أشرطة الأخبار',
            },
        ),
        migrations.CreateModel(
            name='PipeFighterOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='التاريخ')),
                ('shift', models.CharField(choices=[('morning', 'صباحي'), ('night', 'مسائي')], max_length=10, verbose_name='الوردية')),
                ('float_pipes', models.IntegerField(default=0, verbose_name='مواسير عائمة (عدد)')),
                ('float_rubbers', models.IntegerField(default=0, verbose_name='ربرات عائمة (عدد)')),
                ('float_pontoons', models.IntegerField(default=0, verbose_name='طوافات الخط (عدد)')),
                ('float_pantons', models.IntegerField(default=0, verbose_name='بانتون (عدد)')),
                ('float_anchors', models.IntegerField(default=0, verbose_name='مخاطيف الخط (عدد)')),
                ('float_length', models.FloatField(default=0, editable=False, verbose_name='طول الخط العائم')),
                ('land_pipes', models.IntegerField(default=0, verbose_name='مواسير أرضية (عدد)')),
                ('land_rubbers', models.IntegerField(default=0, verbose_name='ربرات أرضية (عدد)')),
                ('land_length', models.FloatField(default=0, editable=False, verbose_name='طول الخط الأرضي')),
                ('total_line_length', models.FloatField(default=0, editable=False, verbose_name='إجمالي طول الخط')),
                ('stock_pipes_new', models.IntegerField(default=0, verbose_name='مواسير جديدة')),
                ('stock_pipes_used', models.IntegerField(default=0, verbose_name='مواسير مستعملة صالحة')),
                ('stock_pipes_scrap', models.IntegerField(default=0, verbose_name='مواسير هالك')),
                ('stock_rubbers_new', models.IntegerField(default=0, verbose_name='ربرات جديدة')),
                ('stock_rubbers_used', models.IntegerField(default=0, verbose_name='ربرات مستعملة صالحة')),
                ('stock_rubbers_scrap', models.IntegerField(default=0, verbose_name='ربرات هالك')),
                ('stock_pontoons_new', models.IntegerField(default=0, verbose_name='طوافات جديدة')),
                ('stock_pontoons_used', models.IntegerField(default=0, verbose_name='طوافات مستعملة صالحة')),
                ('stock_pontoons_scrap', models.IntegerField(default=0, verbose_name='طوافات هالك')),
                ('bolts_30', models.IntegerField(default=0, verbose_name='مسامير 30مم')),
                ('bolts_27', models.IntegerField(default=0, verbose_name='مسامير 27مم')),
                ('wrench_30', models.IntegerField(default=0, verbose_name='مفتاح 30')),
                ('wrench_27', models.IntegerField(default=0, verbose_name='مفتاح 27')),
                ('socket_30', models.IntegerField(default=0, verbose_name='لقمة 30مم')),
                ('socket_27', models.IntegerField(default=0, verbose_name='لقمة 27مم')),
                ('air_gun', models.IntegerField(default=0, verbose_name='ايرجن (عدد)')),
                ('work_description', models.TextField(blank=True, null=True, verbose_name='بيان الأعمال والملاحظات')),
                ('work_photos', models.ImageField(blank=True, null=True, upload_to='pipe_fighter/', verbose_name='صور العمل')),
            ],
            options={
                'verbose_name': 'تقرير بايب فايتر',
                'verbose_name_plural': 'تقارير بايب فايتر',
            },
        ),
        migrations.CreateModel(
            name='SupportEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المعدة')),
                ('category', models.CharField(choices=[('marine', 'معدات بحرية (تتبع الكراكة/المالتي كات)'), ('project', 'معدات برية (تتبع موقع الإدارة والحواجز)')], max_length=20, verbose_name='تصنيف المعدة')),
            ],
            options={
                'verbose_name': 'معدة مساعدة',
                'verbose_name_plural': 'المعدات المساعدة (الأسطول)',
            },
        ),
        migrations.CreateModel(
            name='WeeklyRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الأسبوع (الخميس)')),
                ('active_group', models.CharField(choices=[('A', 'مجموعة A هي العاملة'), ('B', 'مجموعة B هي العاملة')], max_length=1, verbose_name='المجموعة النشطة')),
            ],
            options={
                'verbose_name': 'دوران الورديات الأسبوعي',
                'verbose_name_plural': 'دوران الورديات الأسبوعي',
            },
        ),
        migrations.CreateModel(
            name='Dredger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الكراكة')),
                ('vessel_phone', models.CharField(default='01XXXXXXXXX', max_length=20, verbose_name='تليفون الكراكة')),
                ('is_active', models.BooleanField(default=True, verbose_name='في الخدمة')),
                ('fuel_capacity', models.FloatField(default=0, verbose_name='سعة خزان الكراكة (لتر)')),
                ('stock_fuel', models.FloatField(default=0, verbose_name='السولار المتاح في الاستوك (لتر)')),
                ('allowed_operators', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='المشغلين المسموح لهم')),
            ],
            options={
                'verbose_name': 'كراكة',
                'verbose_name_plural': 'الكراكات',
            },
        ),
        migrations.CreateModel(
            name='DailyProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(verbose_name='تاريخ يوم العمل')),
                ('is_closed', models.BooleanField(default=False, verbose_name='تم إغلاق اليوم')),
                ('dredger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dredger', verbose_name='الكراكة')),
            ],
            options={
                'verbose_name': 'تقرير يومي مجمع',
                'verbose_name_plural': 'التقارير اليومية المجمعة',
            },
        ),
        migrations.CreateModel(
            name='MarineInventoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='اسم الصنف')),
                ('category', models.CharField(choices=[('قايش', 'قايش'), ('أقفال', 'أقفال'), ('حبال', 'حبال'), ('مسامير', 'مسامير'), ('وايرات', 'وايرات'), ('مفاتيح ولقم', 'مفاتيح ولقم'), ('ربرات', 'ربرات'), ('طوافات', 'طوافات'), ('أخرى', 'أخرى')], max_length=50, verbose_name='القسم')),
                ('quantity_found', models.FloatField(default=0, verbose_name='الكمية الموجودة')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.marineinventoryreport')),
            ],
        ),
        migrations.CreateModel(
            name='PipeFighterExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='اسم الصنف الإضافي')),
                ('quantity', models.IntegerField(default=0, verbose_name='العدد / الكمية')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='core.pipefighteroperations')),
            ],
            options={
                'verbose_name': 'صنف إضافي',
                'verbose_name_plural': 'أصناف إضافية للوردية',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم بالكامل')),
                ('group', models.CharField(choices=[('A', 'مجموعة A'), ('B', 'مجموعة B'), ('office', 'الإدارة'), ('other', 'أخرى')], max_length=10, verbose_name='المجموعة (الوردية)')),
                ('team_type', models.CharField(choices=[('dredger', 'طاقم كراكة'), ('pipe_fighter', 'طاقم خط بحري'), ('admin', 'الإدارة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الطاقم')),
                ('role', models.CharField(choices=[('engineer', 'مهندس'), ('supervisor', 'مشرف'), ('manager', 'مدير مشروع'), ('operator', 'مشغل'), ('marine', 'بحرية'), ('mechanic', 'ميكانيكا'), ('admin', 'إداري/سائق')], max_length=30, verbose_name='الوظيفة')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'دليل الموظفين',
            },
        ),
        migrations.AddField(
            model_name='pipefighteroperations',
            name='operator_in_charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='المسؤول'),
        ),
        migrations.AddField(
            model_name='marineinventoryreport',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff', verbose_name='المسؤول'),
        ),
        migrations.CreateModel(
            name='FuelMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='التاريخ والوقت')),
                ('move_type', models.CharField(choices=[('in', 'وارد للموقع (من المورد)'), ('out', 'منصرف لمعدة (استهلاك)')], max_length=5, verbose_name='نوع الحركة')),
                ('source', models.CharField(choices=[('truck', 'عربية السولار (المورد الخارجي)'), ('multicat_tank', 'عهدة المالتي كات (الفنطاس)'), ('admin_tank', 'خزان الموقع الإداري (التانك الأرضي)')], max_length=20, verbose_name='مصدر السولار')),
                ('amount', models.FloatField(verbose_name='الكمية (لتر)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات (رقم بون / اسم السائق)')),
                ('destination_dredger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dredger', verbose_name='الجهة المستلمة: كراكة')),
                ('destination_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supportequipment', verbose_name='الجهة المستلمة: معدة أخرى')),
            ],
            options={
                'verbose_name': 'حركة سولار',
                'verbose_name_plural': 'سجل حركات السولار (الميزان)',
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_time', models.CharField(blank=True, choices=[('morning', 'صباحي (نهار)'), ('night', 'مسائي (ليل)')], max_length=10, null=True, verbose_name='فترة الوردية')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الاستلام/البدء')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم/التوقف')),
                ('start_east', models.FloatField(blank=True, null=True, verbose_name='E البداية')),
                ('start_north', models.FloatField(blank=True, null=True, verbose_name='N البداية')),
                ('end_east', models.FloatField(blank=True, null=True, verbose_name='E النهاية')),
                ('end_north', models.FloatField(blank=True, null=True, verbose_name='N النهاية')),
                ('quantity_m3', models.FloatField(default=0, verbose_name='الكمية المكعبة')),
                ('progress_meters', models.FloatField(default=0, verbose_name='أمتار التقدم (من الخريطة)')),
                ('depth', models.FloatField(default=0, verbose_name='العمق')),
                ('status', models.CharField(choices=[('active', 'تشغيل فعلي (إنتاج)'), ('breakdown_mech', 'عطل ميكانيكي'), ('breakdown_elec', 'عطل كهربائي'), ('maintenance', 'صيانة دورية / عمرة'), ('anchors', 'نقل مخاطيف'), ('maneuver', 'مناورة / تغيير موقع'), ('pipeline', 'فك / تركيب / إصلاح خط الطرد'), ('weather', 'توقف بسبب سوء الأحوال الجوية'), ('waiting_barge', 'انتظار صندل / تموين'), ('safety', 'توقف لأسباب تتعلق بالسلامة'), ('inspection', 'تفتيش / زيارة رسمية'), ('handover', 'استلام وتسليم وردية'), ('other', 'توقف لأسباب أخرى')], default='active', max_length=20, verbose_name='الحالة')),
                ('floating_line', models.FloatField(default=0, verbose_name='طول الخط العائم (م)')),
                ('land_line', models.FloatField(default=0, verbose_name='طول الخط الأرضي (م)')),
                ('stop_reason', models.TextField(blank=True, null=True, verbose_name='سبب التوقف')),
                ('stop_image', models.ImageField(blank=True, null=True, upload_to='stops/%Y/%m/', verbose_name='صورة التوقف')),
                ('main_engine_hours', models.FloatField(default=0, verbose_name='ساعات الماكينة الرئيسية')),
                ('aux_engine_hours', models.FloatField(default=0, verbose_name='ساعات الماكينة المساعدة')),
                ('fuel_usage', models.FloatField(default=0, verbose_name='السولار المستهلك')),
                ('fuel_start', models.FloatField(default=0, verbose_name='كمية السولار بداية الوردية (لتر)')),
                ('fuel_end', models.FloatField(default=0, verbose_name='كمية السولار نهاية الوردية (لتر)')),
                ('fuel_received', models.FloatField(default=0, verbose_name='السولار المستلم/تموين (لتر)')),
                ('main_engine_start', models.FloatField(default=0, verbose_name='ساعة الماكينة الرئيسية (بداية)')),
                ('main_engine_end', models.FloatField(default=0, verbose_name='ساعة الماكينة الرئيسية (نهاية)')),
                ('aux_engine_start', models.FloatField(default=0, verbose_name='ساعة الماكينة المساعدة (بداية)')),
                ('aux_engine_end', models.FloatField(default=0, verbose_name='ساعة الماكينة المساعدة (نهاية)')),
                ('depth_before', models.FloatField(default=0.0, verbose_name='العمق قبل التكريك (م)')),
                ('depth_after', models.FloatField(default=0.0, verbose_name='العمق بعد التكريك (م)')),
                ('swing_width', models.FloatField(default=0.0, verbose_name='عرض السوينج (م)')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='المشغل')),
                ('report_24h', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.dailyprojectreport', verbose_name='اليوم المرتبط')),
            ],
            options={
                'verbose_name': 'سجل وردية',
                'verbose_name_plural': 'سجلات الورديات (Live)',
            },
        ),
    ]
