# Generated by Django 6.0.4 on 2026-05-11 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marineinventoryreport',
            name='report_type',
            field=models.CharField(choices=[('marine', 'جرد كراكة'), ('site', 'جرد موقع')], default='marine', max_length=10, verbose_name='نوع الجرد'),
        ),
        migrations.AlterField(
            model_name='marineinventoryreport',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='marineinventoryreport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marineinventoryreport',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.staff'),
        ),
    ]
