# Generated by Django 6.0.4 on 2026-04-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500, verbose_name='التعليمات / الخبر')),
                ('is_active', models.BooleanField(default=True, verbose_name='تفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'الشريط الإخباري',
                'verbose_name_plural': 'الشريط الإخباري',
            },
        ),
    ]
