# Generated by Django 6.0.4 on 2026-05-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marineinventoryreport_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='assign_to',
            field=models.CharField(choices=[('site', 'مخزن البر (الموقع)'), ('marine', 'جرد الكراكة (البحرية)'), ('pipe', 'تقرير الخط (البايب فيتر)'), ('all', 'يظهر في جميع الأقسام')], default='site', max_length=10, verbose_name='مكان الظهور'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(max_length=100, verbose_name='القسم (مثلاً: حبال، مواسير، عدد)'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='الرصيد الحالي'),
        ),
        migrations.AlterField(
            model_name='marineinventorydetail',
            name='category',
            field=models.CharField(max_length=100, verbose_name='القسم'),
        ),
    ]
