# Generated by Django 6.0.4 on 2026-04-20 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='depth',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workshift',
            name='fuel_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workshift',
            name='main_engine_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='workshift',
            name='progress_meters',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='shift_time',
            field=models.CharField(choices=[('morning', 'صباحي (نهار)'), ('night', 'مسائي (ليل)')], max_length=10),
        ),
    ]
