# Generated by Django 6.0.5 on 2026-05-15 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inventorycategory_inventorytransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='assign_to',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity_marine',
            field=models.FloatField(default=0, verbose_name='رصيد بحرية الكراكة الحالي'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity_pipe',
            field=models.FloatField(default=0, verbose_name='رصيد البايب فيتر الحالي'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity_site',
            field=models.FloatField(default=0, verbose_name='رصيد مخزن البر الحالي'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='show_in_marine',
            field=models.BooleanField(default=False, verbose_name='يظهر في جرد الكراكة (البحرية)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='show_in_pipe',
            field=models.BooleanField(default=False, verbose_name='يظهر في تقرير الخط (البايب فيتر)'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='show_in_site',
            field=models.BooleanField(default=True, verbose_name='يظهر في مخزن البر (الموقع)'),
        ),
        migrations.AddField(
            model_name='marineinventoryreport',
            name='dredger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dredger', verbose_name='الكراكة'),
        ),
        migrations.AddField(
            model_name='pipefighteroperations',
            name='bolts_24',
            field=models.IntegerField(default=0, verbose_name='مسامير 24مم'),
        ),
        migrations.AddField(
            model_name='pipefighteroperations',
            name='socket_24',
            field=models.IntegerField(default=0, verbose_name='لقمة 24مم'),
        ),
        migrations.AddField(
            model_name='pipefighteroperations',
            name='wrench_24',
            field=models.IntegerField(default=0, verbose_name='مفتاح 24مم'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='status',
            field=models.CharField(choices=[('active', 'تشغيل فعلي (إنتاج)'), ('breakdown_mech', 'عطل ميكانيكي'), ('breakdown_elec', 'عطل كهربائي'), ('breakdown_hydrulic', 'عطل هيدروليك'), ('welding', 'أعمال لحام'), ('maintenance', 'صيانة دورية / عمرة'), ('anchors', 'نقل مخاطيف'), ('maneuver', 'مناورة / تغيير موقع'), ('pipeline', 'فك / تركيب / إصلاح خط الطرد'), ('weather', 'توقف بسبب سوء الأحوال الجوية'), ('waiting_barge', 'انتظار صندل / تموين'), ('safety', 'توقف لأسباب تتعلق بالسلامة'), ('inspection', 'تفتيش / زيارة رسمية'), ('handover', 'استلام وتسليم وردية'), ('obstruction', 'عوائق بالتربة'), ('other', 'توقف لأسباب أخرى')], default='active', max_length=20, verbose_name='الحالة'),
        ),
    ]
