# Generated by Django 6.0.4 on 2026-04-20 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adminvault_alter_workshift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='end_east',
            field=models.FloatField(blank=True, null=True, verbose_name='E النهاية'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='end_north',
            field=models.FloatField(blank=True, null=True, verbose_name='N النهاية'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='start_east',
            field=models.FloatField(default=0, verbose_name='E البداية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshift',
            name='start_north',
            field=models.FloatField(default=0, verbose_name='N البداية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workshift',
            name='stop_image',
            field=models.ImageField(blank=True, null=True, upload_to='stops/%Y/%m/', verbose_name='صورة التوقف'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='stop_reason',
            field=models.TextField(blank=True, null=True, verbose_name='سبب التوقف'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='depth',
            field=models.FloatField(default=0, verbose_name='العمق'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='fuel_usage',
            field=models.FloatField(default=0, verbose_name='السولار المستهلك'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='main_engine_hours',
            field=models.FloatField(default=0, verbose_name='ساعات الماكينة'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='المشغل'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='progress_meters',
            field=models.FloatField(default=0, verbose_name='التقدم بالمتر'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='quantity_m3',
            field=models.FloatField(default=0, verbose_name='الكمية المكعبة'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='report_24h',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.dailyprojectreport', verbose_name='مرتبط بيوم عمل'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='shift_time',
            field=models.CharField(choices=[('morning', 'صباحي (نهار)'), ('night', 'مسائي (ليل)')], max_length=10, verbose_name='فترة الوردية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.DateTimeField(verbose_name='وقت الاستلام'),
        ),
    ]
