# Generated by Django 6.0.4 on 2026-04-21 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workshift_end_east_workshift_end_north_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminVault',
        ),
        migrations.DeleteModel(
            name='WeeklyRotation',
        ),
        migrations.AlterModelOptions(
            name='dailyprojectreport',
            options={'verbose_name': 'تقرير يومي مجمع', 'verbose_name_plural': 'التقارير اليومية المجمعة'},
        ),
        migrations.AlterModelOptions(
            name='dredger',
            options={'verbose_name': 'كراكة', 'verbose_name_plural': 'الكراكات'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'verbose_name': 'صنف مخزني', 'verbose_name_plural': 'المخازن'},
        ),
        migrations.AlterModelOptions(
            name='newsticker',
            options={'verbose_name': 'شريط أخبار', 'verbose_name_plural': 'أشرطة الأخبار'},
        ),
        migrations.AlterModelOptions(
            name='pipefighteroperations',
            options={'verbose_name': 'تقرير خط بحري', 'verbose_name_plural': 'تقارير الخطوط البحرية'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'موظف', 'verbose_name_plural': 'دليل الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='workshift',
            options={'verbose_name': 'سجل وردية', 'verbose_name_plural': 'سجلات الورديات (Live)'},
        ),
        migrations.RemoveField(
            model_name='pipefighteroperations',
            name='daily_notes',
        ),
        migrations.RemoveField(
            model_name='pipefighteroperations',
            name='discharge_pipes',
        ),
        migrations.RemoveField(
            model_name='pipefighteroperations',
            name='discharge_rubbers',
        ),
        migrations.RemoveField(
            model_name='pipefighteroperations',
            name='scrapped_rubbers',
        ),
        migrations.RemoveField(
            model_name='pipefighteroperations',
            name='spare_rubbers',
        ),
        migrations.AlterField(
            model_name='dailyprojectreport',
            name='date_started',
            field=models.DateField(verbose_name='تاريخ يوم العمل'),
        ),
        migrations.AlterField(
            model_name='dailyprojectreport',
            name='dredger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dredger', verbose_name='الكراكة'),
        ),
        migrations.AlterField(
            model_name='dailyprojectreport',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='تم إغلاق اليوم'),
        ),
        migrations.AlterField(
            model_name='dredger',
            name='allowed_operators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='المشغلين المسموح لهم'),
        ),
        migrations.AlterField(
            model_name='dredger',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='في الخدمة'),
        ),
        migrations.AlterField(
            model_name='dredger',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الكراكة'),
        ),
        migrations.AlterField(
            model_name='dredger',
            name='vessel_phone',
            field=models.CharField(default='01XXXXXXXXX', max_length=20, verbose_name='تليفون الكراكة'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الصنف'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='الكمية'),
        ),
        migrations.AlterField(
            model_name='pipefighteroperations',
            name='crew_present',
            field=models.ManyToManyField(related_name='pf_present', to='core.staff', verbose_name='الطاقم الحاضر'),
        ),
        migrations.AlterField(
            model_name='pipefighteroperations',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='pipefighteroperations',
            name='scrapped_pipes',
            field=models.IntegerField(default=0, verbose_name='مواسير هالك'),
        ),
        migrations.AlterField(
            model_name='pipefighteroperations',
            name='shift',
            field=models.CharField(choices=[('morning', 'نهار'), ('night', 'ليل')], max_length=10, verbose_name='الوردية'),
        ),
        migrations.AlterField(
            model_name='pipefighteroperations',
            name='spare_pipes',
            field=models.IntegerField(default=0, verbose_name='مواسير احتياطي'),
        ),
        migrations.AlterField(
            model_name='pipefighteroperations',
            name='work_photos',
            field=models.ImageField(blank=True, null=True, upload_to='pf_daily/', verbose_name='صور العمل'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='group',
            field=models.CharField(choices=[('A', 'مجموعة A'), ('B', 'مجموعة B')], max_length=1, verbose_name='المجموعة (الوردية)'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='team_type',
            field=models.CharField(choices=[('dredger', 'طاقم كراكة'), ('pipe', 'طاقم خط بحري')], max_length=10, verbose_name='نوع الطاقم'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='report_24h',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='core.dailyprojectreport', verbose_name='اليوم المرتبط'),
        ),
    ]
