# Generated by Django 6.0.4 on 2026-04-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_adminvault_delete_weeklyrotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminVault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='اسم الموظف')),
                ('username', models.CharField(max_length=50, verbose_name='اسم المستخدم')),
                ('password_plain', models.CharField(max_length=50, verbose_name='كلمة المرور (للتذكير)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'سجل حساب سري',
                'verbose_name_plural': 'خزنة الحسابات السرية',
            },
        ),
    ]
