# Generated by Django 6.0.5 on 2026-05-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_workshift_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='status',
            field=models.CharField(choices=[('active', 'تشغيل فعلي (إنتاج)'), ('breakdown_mech', 'عطل ميكانيكي'), ('breakdown_elec', 'عطل كهربائي'), ('breakdown_hydrulic', 'عطل هيدروليك'), ('welding', 'أعمال لحام'), ('maintenance', 'صيانة دورية / عمرة'), ('anchors', 'نقل مخاطيف'), ('maneuver', 'تشفيت / تغيير موقع'), ('pipeline_washed', 'غسيل خط/ضخ مياه'), ('pipeline', 'فك / تركيب / إصلاح خط الطرد'), ('weather', 'توقف بسبب سوء الأحوال الجوية'), ('waiting_barge', 'انتظار صندل / تموين'), ('safety', 'توقف لأسباب تتعلق بالسلامة'), ('inspection', 'تفتيش / زيارة رسمية'), ('handover', 'استلام وتسليم وردية'), ('shift_end', 'نهاية وردية ( 12 ساعة)'), ('obstruction', 'عوائق بالتربة'), ('stone_box', 'فتح صندوق الحجارة'), ('cutter_check', 'التشييك على الكتر'), ('pipe_change', 'تغيير ماسورة بالخط'), ('rubber_change', 'تغيير رابر بالخط'), ('other', 'توقف لأسباب أخرى')], default='active', max_length=20, verbose_name='الحالة'),
        ),
    ]
