# Generated by Django 6.0.5 on 2026-05-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_workshift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprojectreport',
            name='show_quantity_in_report',
            field=models.BooleanField(default=True, verbose_name='إظهار إجمالي المكعبات في التقرير المطبوع'),
        ),
    ]
