# Generated by Django 6.0.4 on 2026-04-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_adminvault'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الأسبوع (الأربعاء)')),
                ('active_group', models.CharField(choices=[('A', 'مجموعة A هي العاملة'), ('B', 'مجموعة B هي العاملة')], max_length=1, verbose_name='المجموعة النشطة')),
            ],
            options={
                'verbose_name': 'دوران الورديات الأسبوعي',
                'verbose_name_plural': 'دوران الورديات الأسبوعي',
            },
        ),
    ]
