# Generated by Django 6.0.5 on 2026-06-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dailyprojectreport_show_quantity_in_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorytransaction',
            options={'verbose_name': 'معاملة جرد', 'verbose_name_plural': 'سجل معاملات الجرد'},
        ),
        migrations.AddField(
            model_name='dailyprojectreport',
            name='frozen_aux_net',
            field=models.CharField(default='00:00', max_length=10, verbose_name='صافي ساعات المساعد المجمد'),
        ),
        migrations.AddField(
            model_name='dailyprojectreport',
            name='frozen_fuel_usage',
            field=models.FloatField(default=0.0, verbose_name='استهلاك السولار المجمد'),
        ),
        migrations.AddField(
            model_name='dailyprojectreport',
            name='frozen_main_net',
            field=models.CharField(default='00:00', max_length=10, verbose_name='صافي ساعات الرئيسي المجمد'),
        ),
        migrations.AddField(
            model_name='dailyprojectreport',
            name='frozen_stop_hours',
            field=models.CharField(default='00:00', max_length=10, verbose_name='ساعات التوقف المجمدة'),
        ),
        migrations.AddField(
            model_name='dailyprojectreport',
            name='frozen_total_m3',
            field=models.FloatField(default=0.0, verbose_name='إجمالي المكعبات المجمدة'),
        ),
        migrations.AddField(
            model_name='dailyprojectreport',
            name='frozen_total_meters',
            field=models.FloatField(default=0.0, verbose_name='إجمالي الأمتار المجمدة'),
        ),
        migrations.AddField(
            model_name='dailyprojectreport',
            name='frozen_work_hours',
            field=models.CharField(default='00:00', max_length=10, verbose_name='ساعات التشغيل المجمدة'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='status',
            field=models.CharField(choices=[('active', 'تشغيل فعلي (إنتاج)'), ('breakdown_mech', 'عطل ميكانيكي'), ('breakdown_elec', 'عطل كهربائي'), ('breakdown_hydrulic', 'عطل هيدروليك'), ('welding', 'أعمال لحام'), ('maintenance', 'صيانة دورية / عمرة'), ('anchors', 'نقل مخاطيف'), ('maneuver', 'تشفيت / تغيير موقع'), ('pipeline_washed', 'غسيل خط/ضخ مياه'), ('pipeline', 'فك / تركيب / إصلاح خط الطرد'), ('weather', 'توقف بسبب سوء الأحوال الجوية'), ('waiting_barge', 'انتظار صندل / تموين'), ('safety', 'توقف لأسباب تتعلق بالسلامة'), ('inspection', 'تفتيش / زيارة رسمية'), ('handover', 'استلام وتسليم وردية'), ('shift_end', 'نهاية وردية ( 12 ساعة)'), ('obstruction', 'عوائق بالتربة'), ('stone_box', 'فتح صندوق الحجارة'), ('cutter_check', 'التشييك على الكتر'), ('pipe_change', 'تغيير ماسورة بالخط'), ('rubber_change', 'تغيير رابر بالخط'), ('other', 'توقف لأسباب أخرى')], default='other', max_length=20, verbose_name='الحالة'),
        ),
    ]
