# Generated by Django 6.0.4 on 2026-04-22 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_weeklyrotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='aux_engine_hours',
            field=models.FloatField(default=0, verbose_name='ساعات الماكينة المساعدة'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التسليم/التوقف'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='main_engine_hours',
            field=models.FloatField(default=0, verbose_name='ساعات الماكينة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='shift_time',
            field=models.CharField(blank=True, choices=[('morning', 'صباحي (نهار)'), ('night', 'مسائي (ليل)')], max_length=10, null=True, verbose_name='فترة الوردية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_east',
            field=models.FloatField(blank=True, null=True, verbose_name='E البداية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_north',
            field=models.FloatField(blank=True, null=True, verbose_name='N البداية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الاستلام/البدء'),
        ),
    ]
