# Generated by Django 6.0.4 on 2026-04-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workshift_aux_engine_hours_alter_workshift_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='floating_line',
            field=models.FloatField(default=0, verbose_name='طول الخط العائم (م)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='land_line',
            field=models.FloatField(default=0, verbose_name='طول الخط الأرضي (م)'),
        ),
    ]
