# Generated by Django 6.0.5 on 2026-06-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_inventorytransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='fuel_to_dredger',
            field=models.FloatField(default=0.0, verbose_name='سولار منقول لكراكة أخرى (لتر)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='fuel_to_excavator',
            field=models.FloatField(default=0.0, verbose_name='سولار منقول لحفار خدمة (لتر)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='fuel_to_multicat',
            field=models.FloatField(default=0.0, verbose_name='سولار منقول لمعدة بحرية/مالتي كات (لتر)'),
        ),
    ]
