# Generated by Django 6.0.4 on 2026-04-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workshift_floating_line_workshift_land_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='status',
            field=models.CharField(choices=[('active', 'في الخدمة (تكريك فعلي)'), ('maint_plan', 'توقف للصيانة الدورية'), ('anchors', 'توقف لنقل المخاطيف'), ('pipe_line', 'توقف لصيانة خط الطرد'), ('water_pump', 'توقف تكريك لضخ مياه في الخط'), ('shifting', 'توقف لتشفيت الكراكة'), ('wire_break', 'توقف لانقطاع واير'), ('breakdown', 'توقف لعطل فني مفاجئ'), ('basin', 'توقف بسبب حوض الترسيب'), ('other', 'توقف لأسباب أخرى')], default='active', max_length=20, verbose_name='الحالة'),
        ),
    ]
