# Generated by Django 6.0.5 on 2026-06-08 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workshift_fuel_to_dredger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('pipe_rubber', '🚨 قطع رابر بخط الطرد'), ('pipe_crack', '🚨 شرخ ماسورة بخط الطرد'), ('pipe_out', '🚨 خروج الخط عن المسار'), ('fuel_urg', '🚨 طلب تموين سولار عاجل')], max_length=30, verbose_name='نوع الطوارئ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='توقيت البلاغ')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم التعامل وحل المشكلة')),
                ('dredger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.dredger', verbose_name='الكراكة')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='المُبلّغ')),
            ],
            options={
                'verbose_name': 'بلاغ طوارئ وعطل عاجل',
                'verbose_name_plural': 'بلاغات الطوارئ الأعطال العاجلة',
            },
        ),
    ]
