# Generated by Django 6.0.4 on 2026-04-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_workshift_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dredger',
            name='fuel_capacity',
            field=models.FloatField(default=0, verbose_name='سعة خزان الكراكة (لتر)'),
        ),
        migrations.AddField(
            model_name='dredger',
            name='stock_fuel',
            field=models.FloatField(default=0, verbose_name='السولار المتاح في الاستوك (لتر)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='fuel_added',
            field=models.FloatField(default=0, verbose_name='سولار مضاف للكراكة (تموين)'),
        ),
    ]
