# Generated by Django 6.0.5 on 2026-06-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_emergencyalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='depth_after',
            field=models.FloatField(blank=True, null=True, verbose_name='العمق بعد التكريك (م)'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='depth_before',
            field=models.FloatField(blank=True, null=True, verbose_name='العمق قبل التكريك (م)'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='main_engine_hours',
            field=models.FloatField(default=0, verbose_name='sاعات الماكينة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='progress_meters',
            field=models.FloatField(blank=True, null=True, verbose_name='أمتار التقدم (من الخريطة)'),
        ),
        migrations.AlterField(
            model_name='workshift',
            name='swing_width',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض السوينج (م)'),
        ),
    ]
