# Generated by Django 6.0.5 on 2026-06-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_workshift_depth_after_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='اسم العنصر / القطعة المطلوب شراءها')),
                ('quantity', models.CharField(max_length=100, verbose_name='الكمية والمواصفة الفنية')),
                ('status', models.CharField(choices=[('pending', '⏳ طلب معلق (قيد الدراسة)'), ('purchased', '💳 تم الشراء (في الطريق للموقع)'), ('delivered', '✅ وصل الموقع وتم الاستلام'), ('cancelled', '❌ تم إلغاء الطلب')], default='pending', max_length=20, verbose_name='حالة التنفيذ الحالية')),
                ('date_requested', models.DateField(auto_now_add=True, verbose_name='تاريخ طلب الشراء التلقائي')),
                ('date_executed', models.DateField(blank=True, null=True, verbose_name='تاريخ تنفيذ الشراء الفعلي')),
                ('date_delivered', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام في الميناء')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='التكلفة التقديرية / الفعلية')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة والفواتير')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff', verbose_name='المهندس / الكابتن طالب الشراء')),
            ],
            options={
                'verbose_name': 'طلب شراء لوجستي',
                'verbose_name_plural': 'خزان المشتريات والقطع',
                'ordering': ['-date_requested', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='FuelMovement',
        ),
    ]
