# Generated by Django 6.0.4 on 2026-04-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dredger_fuel_capacity_dredger_stock_fuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshift',
            name='aux_engine_end',
            field=models.FloatField(default=0, verbose_name='ساعة الماكينة المساعدة (نهاية)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='aux_engine_start',
            field=models.FloatField(default=0, verbose_name='ساعة الماكينة المساعدة (بداية)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='fuel_end',
            field=models.FloatField(default=0, verbose_name='كمية السولار نهاية الوردية (لتر)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='fuel_received',
            field=models.FloatField(default=0, verbose_name='السولار المستلم/تموين (لتر)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='fuel_start',
            field=models.FloatField(default=0, verbose_name='كمية السولار بداية الوردية (لتر)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='main_engine_end',
            field=models.FloatField(default=0, verbose_name='ساعة الماكينة الرئيسية (نهاية)'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='main_engine_start',
            field=models.FloatField(default=0, verbose_name='ساعة الماكينة الرئيسية (بداية)'),
        ),
    ]
