# Generated by Django 6.0.5 on 2026-06-13 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_procurementorder_delete_fuelmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dredger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.dredger', verbose_name='الكراكة المعين عليها'),
        ),
    ]
