# Generated by Django 6.0.4 on 2026-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_workshift_aux_engine_end_workshift_aux_engine_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshift',
            name='progress_meters',
            field=models.FloatField(default=0, verbose_name='أمتار التقدم (من الخريطة)'),
        ),
    ]
